adata_path: "D:\\peak2vec\\pbmc10k_atac_filtered.h5ad"
outdir: "D:\\peak2vec\\pbmc10k_test"

preprocessing:
  chrom_col: Chromosome
  start_col: Start
  end_col: End
  center_col: Center
  source: var_names
  peak_name_col: null
  overwrite: false

sampling:
  samples_per_epoch: 20000
  n_pairs: 20
  n_negative: 20
  trans_fraction: 0.2
  cis_window: 500000
  same_chr_negative_prob: 0.5
  subsample_t: 5.0e-7
  neg_power: 0.75

train:
  embedding_dim: 128
  pos_weight: 2.0
  sparse: false
  tie_weights: false
  lr: 0.015
  weight_decay: 0.003
  batch_size: 512
  epochs: 10
  seed: 4
  device: auto
  num_workers: 0
  pin_memory: true
  checkpoint_every_epochs: 2
  save_embeddings_every_epochs: 5
  grad_clip_norm: null

wandb:
  project: peak2vec
  entity: claptar
  group: null
  name: peak2vec-test
  tags: []
  mode: online
  save_table: true
  n_per_chromosome: 200
  visualize_embeddings: true
  viz_metadata_cols:
    - Chromosome
  viz_n_neighbors: 15
  viz_metric: cosine